# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_one', models.CharField(max_length=100)),
                ('address_two', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('stripe_id', models.CharField(blank=True, max_length=30)),
                ('user_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.User')),
            ],
            options={
                'verbose_name_plural': 'subscribers',
            },
        ),
    ]
