# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 01:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserNew',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
