# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20171106_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='state',
            new_name='province',
        ),
    ]
